DROP TABLE IF EXISTS Buyer CASCADE;
DROP TABLE IF EXISTS Spectator CASCADE;
DROP TABLE IF EXISTS Game CASCADE; 
DROP TABLE IF EXISTS Price CASCADE;
DROP TABLE IF EXISTS Booking CASCADE;

DROP TYPE IF EXISTS buyer_civ;
DROP TYPE IF EXISTS spectator_civ;
DROP TYPE IF EXISTS booking_price;
DROP TYPE IF EXISTS price_type;